INSERT INTO FILECATEGORY VALUES ('test', '2020-03-10');
INSERT INTO FILECATEGORY VALUES ('test2', '2020-03-11');

INSERT INTO FILEVERSION (NAME, VERSION, CONTENT, CREATED, CATEGORY) VALUES ('test', 1, 'test content', '2021-03-10', 'test');
INSERT INTO FILEVERSION (NAME, VERSION, CONTENT, CREATED, CATEGORY) VALUES ('test', 2, 'test content', '2021-03-10', 'test');
INSERT INTO FILEVERSION (NAME, VERSION, CONTENT, CREATED, CATEGORY) VALUES ('test2', 1, 'test content', '2021-03-11', 'test2');
