quarkus.datasource.db-kind=mariadb
quarkus.datasource.username=sftp
quarkus.datasource.password=sftp4test
quarkus.datasource.jdbc.url=jdbc:mariadb://${DB_HOST}:3306/sftp
quarkus.datasource.jdbc.max-size=13

quarkus.datasource.db-version=10.5.19

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
