quarkus.datasource.db-kind=h2
quarkus.datasource.username=sftp
#quarkus.datasource.password=sftp4test
quarkus.datasource.jdbc.url=jdbc:h2:mem:default
quarkus.datasource.jdbc.max-size=13

#quarkus.datasource.db-version=10.5.19

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
